# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2045e0cdae980ceb93c166cb49f1f2566bd8ae87e2b7254042f53178645fae1e59b70b5e3c1d19b80dc7ff10be3843e29f725c208e03c2e2e8cf6e8b79d999a6

test:
  secret_key_base: ef010fe9ffac808519d464ad610b740667a91a8dae8728e4f7fb8b5c7444ef52f6c8cbb958d11b06f8ba98d73dcc71664f6f17308ad080c5db7aa25f9dffb2e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
